var LANG_ARR =
{
	"bn" :
	{
		"0" : "০",
		"1" : "১",
		"2" : "২",
		"3" : "৩",
		"4" : "৪",
		"5" : "৫",
		"6" : "৬",
		"7" : "৭",
		"8" : "৮",
		"9" : "৯",

		"counting" : "গণনা",
		"energy" : "শক্তি",
		"length" : "দৈর্ঘ্য",
		"mass" : "ভর",
		"power" : "ক্ষমতা",
		"pressure" : "চাপ",
		"speed" : "গতি",
		"temperature" : "তাপমাত্রা",
		"time" : "সময়",
		"volume" : "আয়তন",

		"unit" : "একক",
		"couple" : "জুটি",
		"pair" : "জোড়া",
		"dozen" : "ডজন",
		"gross" : "গ্রস",
		"score" : "স্কোর",

		"calorie_nutritional" : "ক্যালরি (পুষ্টি)",
		"calorie_thermochemical" : "ক্যালরি (তাপরাসায়নিক)",
		"electron_volt" : "ইলেকট্রন ভোল্ট",
		"erg" : "ই আর জি",
		"joule" : "জুল",
		"newton_meter" : "নিউটন-মিটার",
		"watt_hour" : "ওয়াট-ঘন্টা",

		"angstrom" : "অ্যাংস্ট্রম",
		"chain" : "চেইন",
		"fathom" : "ফ্যাদম",
		"foot" : "ফুট",
		"furlong" : "ফারলং",
		"inch" : "ইঞ্চি",
		"league" : "লিগ",
		"light_year" : "আলোকবর্ষ",
		"meter" : "মিটার",
		"mile" : "মাইল",
		"nautical_mile" : "নটিক্যাল মাইল",
		"rod" : "রড",
		"yard" : "ইয়ার্ড",

		"atomic_mass_unit" : "পারমাণবিক ভর একক",
		"carat" : "ক্যারাট",
		"cental" : "সেন্টাল",
		"dram" : "ড্রাম",
		"grain" : "গ্রেইন",
		"gram" : "গ্রাম",
		"ounce" : "আউনস",
		"pennyweight" : "পেনিওয়েট",
		"pound" : "পাউন্ড",
		"quarter" : "কোয়ার্টার",
		"stone" : "স্টোন",
		"tonne" : "টন",

		"calories_per_second" : "ক্যালরি/সেকেন্ড",
		"horsepower" : "অশ্বশক্তি",
		"watt" : "ওয়াট",

		"atmosphere" : "অ্যাটমস্ফিয়ার",
		"bar" : "বার",
		"kilograms_per_square_meter" : "কিলোগ্রাম / বর্গমিটার",
		"milimeter_of_mercury" : "মিলিমিটার পারদ",
		"pascal" : "প্যাসকেল",
		"torr" : "টর",

		"feet_per_second" : "ফুট/সেকেন্ড",
		"kilometers_per_hour" : "কিলোমিটার/ঘন্টা",
		"knot" : "নট",
		"meters_per_second" : "মিটার/সেকেন্ড",
		"miles_per_hour" : "মাইল/ঘন্টা",
		"speed_of_light" : "আলোর গতি",
		"speed_of_sound" : "শব্দের গতি",

		"millennium" : "শহস্রাব্দ",
		"century" : "শতাব্দি",
		"decade" : "দশক",
		"julian_year": "জুলিয়ান বছর",
		"gregorian_year" : "গ্রেগরিয়ান বছর",
		"tropical_year" : "উপকূলীয় বছর",
		"year" : "বছর",
		"month" : "মাস",
		"fortnight" : "পক্ষ",
		"week" : "সপ্তাহ",
		"day" : "দিন",
		"hour" : "ঘন্টা",
		"minute" : "মিনিট",
		"second" : "সেকেন্ড",

		"yocto" : "ইয়ক্টো",
		"zepto" : "জেপটো",
		"atto" : "অ্যাটো",
		"femto" : "ফেমটো",
		"pico" : "পিকো",
		"nano" : "ন্যানো",
		"micro" : "মাইক্রো",
		"milli" : "মিলি",
		"centi" : "সেন্টি",
		"deci" : "ডেসি",
		"multiplier" : "গুণক",
		"deka" : "ডেকা",
		"hecto" : "হেক্টো",
		"kilo" : "কিলো",
		"mega" : "মেগা",
		"giga" : "গিগা",
		"tera" : "টেরা",
		"peta" : "পেটা",
		"exa" : "এক্সা",
		"zetta" : "জেটা",
		"yotta" : "ইয়োটা",

		"cubic_centimeter" : "কিউবিক সেন্টিমিটার",
		"cubic_foot" : "কিউবিক ফুট",
		"cubic_inch" : "কিউবিক ইঞ্চি",
		"cubic_meter" : "কিউবিক মিটার",
		"cubic_milimeter" : "কিউবিক মিলিমিটার",
		"gallon" : "গ্যালন",
		"liter" : "লিটার",
		"pint" : "পাইন্ট",
		"quart" : "কোয়ার্ট",

		"title": "সহজ ইউনিট কনভার্টার",
		"title_text" : "সহজ ইউনিট কনভার্টার",
		"point" : ".",
		"e" : "ই",
		"main_menu" : "মেইন মেনু",
		"from_input_placeholder": "৪ দশমিক ঘর"
	},



	"en" :
	{
		"title": "Ezzee Unit converter",
		"title_text" : "Ezzee Unit Converter",
		"point" : ".",
		"main_menu" : "Main menu",
		"e" : "E",
		"from_input_placeholder": "4 decimal places"
	}
}
